//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyKindergarden
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitDateSupportTable
    {
        public bool Id { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
