//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyKindergarden
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitNote
    {
        public int Id { get; set; }
        public int Child_Id { get; set; }
        public int VisitDate_Id { get; set; }
        public Nullable<bool> Visited { get; set; }
        public string Additional { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual VisitDate VisitDate { get; set; }
    }
}
